---

- name: 'RockyLinux - install package epel-release'
  ansible.builtin.package:
    name: 'epel-release'
    state: 'present'
  when: 'ansible_distribution == "Rocky"'
  notify:
    - 'RockyLinux - install epel-release key'
    - "Run 'dnf makecache'"

- meta: flush_handlers
