---

- name: 'RockyLinux - install package epel-release'
  yum:
    name: 'epel-release'
    state: 'present'
  when: 'ansible_distribution == "Rocky"'
  notify:
    - "run 'dnf makecache'"

- name: 'RockyLinux - install epel-release key'
  rpm_key:
    key: '/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}'
    state: 'present'
  when: 'ansible_distribution == "Rocky"'
  ignore_errors: "{{ ansible_check_mode |default(false)}}"

- meta: flush_handlers
